backend:
  name: github
  repo: cesi-it-aix/website
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: 'post'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image', required: false }
      - label: 'Date'
        name: 'date'
        widget: 'date'
        format: 'YYYY-MM-DD'
        required: false
      - { label: 'Hidden', name: 'hidden', widget: 'boolean', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    extension: mdx
    format: frontmatter
