backend:
  name: github
  repo: cesi-it-aix/website
  branch: master

media_folder: static/uploads
public_folder: /uploads

site_url: https://bde-cesi-aix.fr

collections:
  - name: 'events'
    label: 'Events'
    folder: 'content/events'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image', required: false }
      - label: 'Date'
        name: 'date'
        widget: 'date'
        format: 'YYYY-MM-DD'
      - { label: 'Body', name: 'body', widget: 'markdown' }
    extension: mdx
    format: frontmatter
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
    extension: mdx
    format: frontmatter
